import { Song } from "@/types/song";

export const INITIAL_MOCK_SONGS: Song[] = [
  {
    id: "song-001",
    titre: "About Damn Time",
    artiste: "Lizzo",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré mineur (D-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-002",
    titre: "Ain't No Mountain High Enough",
    artiste: "Marvin Gaye & Tammi Terrell",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do# mineur (C#-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-003",
    titre: "Ain't No Sunshine",
    artiste: "Bill Withers",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : La mineur (A-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-004",
    titre: "All About That Bass",
    artiste: "Meghan Trainor",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si bémol (Bb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-005",
    titre: "All Night Long",
    artiste: "Lionel Richie",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa (F)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-006",
    titre: "Always Remember Us This Way",
    artiste: "Lady Gaga",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol mineur (G-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-007",
    titre: "As It Was",
    artiste: "Harry Styles",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi (E)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-008",
    titre: "Attention",
    artiste: "Charlie Puth",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré mineur (D-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-009",
    titre: "Back To Black",
    artiste: "Amy Winehouse",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré mineur (D-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-010",
    titre: "Bad Guy",
    artiste: "Billie Eilish",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol mineur (G-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-011",
    titre: "Bad Guy Acoustic",
    artiste: "Billie Eilish",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol mineur (G-) — Version acoustique",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-012",
    titre: "Balance Ton Quoi",
    artiste: "Angèle",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do (C)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-013",
    titre: "Bam Bam",
    artiste: "Camila Cabello ft. Ed Sheeran",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol bémol (Gb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-014",
    titre: "Beautiful Things",
    artiste: "Benson Boone",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi bémol (Eb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-015",
    titre: "Bellyache",
    artiste: "Billie Eilish",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do (C)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-016",
    titre: "Billie Jean",
    artiste: "Michael Jackson",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa# mineur (F#-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-017",
    titre: "Bird Of a Feather",
    artiste: "Billie Eilish",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré (D)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-018",
    titre: "Black Horse and Cherry Tree",
    artiste: "KT Tunstall",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi mineur (E-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-019",
    titre: "Blinding Lights",
    artiste: "The Weeknd",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi (E)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-020",
    titre: "Boy",
    artiste: "Lee Hargreaves",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré bémol (Db)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-021",
    titre: "Can't Stop The Feeling",
    artiste: "Justin Timberlake",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do (C)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-022",
    titre: "C'est bon",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi bémol (Eb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-023",
    titre: "Cette année là",
    artiste: "Claude François",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si (B)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-024",
    titre: "Crazy",
    artiste: "Gnarls Barkley",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do mineur (C-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-025",
    titre: "Cry Me A River",
    artiste: "Julie London",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si bémol (Bb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-026",
    titre: "Daisies",
    artiste: "Katy Perry",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do (C)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-027",
    titre: "Dangerous Woman",
    artiste: "Ariana Grande",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi mineur (E-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-028",
    titre: "Désenchantée",
    artiste: "Mylène Farmer",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : La mineur (A-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-029",
    titre: "Don't Worry",
    artiste: "Madcon",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do mineur (C-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-030",
    titre: "Encore un soir",
    artiste: "Céline Dion",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si (B)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-031",
    titre: "Espresso",
    artiste: "Sabrina Carpenter",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : La mineur (A-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-032",
    titre: "Etre un homme comme vous",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi bémol (Eb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-033",
    titre: "Fallin'",
    artiste: "Alicia Keys",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi mineur (E-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-034",
    titre: "Feel Like A Woman",
    artiste: "Shania Twain",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si (B)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-035",
    titre: "Fever",
    artiste: "Peggy Lee",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : La mineur (A-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-036",
    titre: "FourFiveSeconds",
    artiste: "Rihanna & Kanye West & Paul McCartney",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do (C)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-037",
    titre: "Freed From Desire",
    artiste: "Gala",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré mineur (D-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-038",
    titre: "From The Start",
    artiste: "Laufey",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré bémol (Db)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-039",
    titre: "F#*k You, Forget You",
    artiste: "CeeLo Green",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do (C)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-040",
    titre: "Georgia On My Mind",
    artiste: "Ray Charles",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si bémol (Bb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-041",
    titre: "Good In Bed",
    artiste: "Dua Lipa",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa (F)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-042",
    titre: "Grace Kelly",
    artiste: "Mika",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol (G)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-043",
    titre: "Hallelujah",
    artiste: "Leonard Cohen",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi (E)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-044",
    titre: "Hips Don't Lie",
    artiste: "Shakira",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si bémol mineur (Bb-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-045",
    titre: "Hit Me Baby One More Time",
    artiste: "Britney Spears",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do mineur (C-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-046",
    titre: "Hot'n Cold",
    artiste: "Katy Perry",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa (F)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-047",
    titre: "How Deep Is Your Love?",
    artiste: "Bee Gees",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol bémol (Gb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-048",
    titre: "I Can't Feel My Face",
    artiste: "The Weeknd",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : La mineur (A-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-049",
    titre: "I Kissed A Girl",
    artiste: "Katy Perry",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol mineur (G-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-050",
    titre: "If I Ain't Got You",
    artiste: "Alicia Keys",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol (G)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-051",
    titre: "Il en faut peu",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do (C)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-052",
    titre: "Il jouait du piano debout",
    artiste: "Michel Sardou",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi bémol (Eb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-053",
    titre: "I'm Outta Love",
    artiste: "Anastacia",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol# mineur (G#-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-054",
    titre: "I'm Yours (Joelle - D)",
    artiste: "Jason Mraz",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do (C) — Version Joëlle (transposée Ré)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-055",
    titre: "I'm Yours (Tine - C)",
    artiste: "Jason Mraz",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do (C) — Version Tine",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-056",
    titre: "Is This Love?",
    artiste: "Bob Marley",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol mineur (G-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-057",
    titre: "Isn't She Lovely",
    artiste: "Stevie Wonder",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi (E)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-058",
    titre: "It's Not Unusual",
    artiste: "Tom Jones",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré bémol (Db)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-059",
    titre: "I Won't Go For More",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré mineur (D-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-060",
    titre: "J'attends",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa (F)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-061",
    titre: "Jardin d'hiver",
    artiste: "Henri Salvador",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa# mineur (F#-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-062",
    titre: "Je ne veux pas travailler",
    artiste: "Pink Martini",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa (F)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-063",
    titre: "Je t'aimais, je t'aime et je t'aimerai",
    artiste: "Francis Cabrel",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : La (A)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-064",
    titre: "Just Two Of Us",
    artiste: "Grover Washington Jr.",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa mineur (F-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-065",
    titre: "L-O-V-E",
    artiste: "Nat King Cole",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa (F)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-066",
    titre: "L'air du vent",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do (C)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-067",
    titre: "La Corrida",
    artiste: "Francis Cabrel",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa# mineur (F#-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-068",
    titre: "La Grenade",
    artiste: "Clara Luciani",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si mineur (B-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-069",
    titre: "La Groupie Du Pianiste",
    artiste: "Alain Souchon",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si mineur (B-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-070",
    titre: "Laissez moi danser",
    artiste: "Dalida",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré (D)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-071",
    titre: "Late Night Talking",
    artiste: "Harry Styles",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si bémol (Bb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-072",
    titre: "Le temps est bon",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa mineur (F-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-073",
    titre: "Le temps fera les choses",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : La mineur (A-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-074",
    titre: "Les Demons De Minuit",
    artiste: "Images",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré mineur (D-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-075",
    titre: "Levitating",
    artiste: "Dua Lipa",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si mineur (B-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-076",
    titre: "Lost In Japan",
    artiste: "Shawn Mendes",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré (D)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-077",
    titre: "Love On Top",
    artiste: "Beyoncé",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol (G)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-078",
    titre: "Love Yourself",
    artiste: "Justin Bieber",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré (D)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-079",
    titre: "Ma philosophie",
    artiste: "Amel Bent",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi mineur (E-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-080",
    titre: "Man In The Mirror",
    artiste: "Michael Jackson",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do (C)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-081",
    titre: "Melodrama",
    artiste: "Lorde",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi bémol (Eb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-082",
    titre: "Oh Madeleine",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa (F)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-083",
    titre: "Onde Sensuelle",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré (D)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-084",
    titre: "Perfect",
    artiste: "Ed Sheeran",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : La (A)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-085",
    titre: "Peur des filles",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do# mineur (C#-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-086",
    titre: "Pretty Please",
    artiste: "Dua Lipa",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol bémol (Gb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-087",
    titre: "Price Tag",
    artiste: "Jessie J",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi bémol (Eb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-088",
    titre: "Raggamuffin",
    artiste: "Selah Sue",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol mineur (G-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-089",
    titre: "Respire encore",
    artiste: "Clara Luciani",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si mineur (B-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-090",
    titre: "Résiste",
    artiste: "France Gall",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol mineur (G-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-091",
    titre: "Risk It All",
    artiste: "The Vamps",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré (D)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-092",
    titre: "Say a Little Prayer",
    artiste: "Aretha Franklin",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa (F)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-093",
    titre: "Say My Name",
    artiste: "Destiny's Child",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do mineur (C-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-094",
    titre: "September",
    artiste: "Earth, Wind & Fire",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : La (A)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-095",
    titre: "Shake It Off",
    artiste: "Taylor Swift",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol bémol (Gb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-096",
    titre: "Shallow",
    artiste: "Lady Gaga & Bradley Cooper",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa (F)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-097",
    titre: "So Easy To Fall In Love",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi bémol (Eb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-098",
    titre: "Soleil Bleu",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : La mineur (A-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-099",
    titre: "Soleil Soleil",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : La mineur (A-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-100",
    titre: "Soulman",
    artiste: "Ben E. King",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do (C)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-101",
    titre: "Stand By Me",
    artiste: "Ben E. King",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si (B)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-102",
    titre: "Suddenly I See",
    artiste: "KT Tunstall",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré (D)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-103",
    titre: "Sunrise",
    artiste: "Norah Jones",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi bémol (Eb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-104",
    titre: "Thinking Out Loud",
    artiste: "Ed Sheeran",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Ré (D)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-105",
    titre: "This Love",
    artiste: "Maroon 5",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do mineur (C-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-106",
    titre: "Toxic",
    artiste: "Britney Spears",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si bémol mineur (Bb-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-107",
    titre: "Treasure (Tine - Cm)",
    artiste: "Bruno Mars",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do mineur (C-) — Version Tine",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-108",
    titre: "Valerie (Joelle - Gb)",
    artiste: "Amy Winehouse",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi (E) — Version Joëlle (transposée Sol bémol)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-109",
    titre: "Valerie (Tine - E)",
    artiste: "Amy Winehouse",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi (E) — Version Tine",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-110",
    titre: "Virtual Insanity",
    artiste: "Jamiroquai",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa mineur (F-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-111",
    titre: "Wait For A Moment",
    artiste: "Artefacts",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa (F)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-112",
    titre: "Wannabe",
    artiste: "Spice Girls",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : La (A)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-113",
    titre: "Water",
    artiste: "Tyla",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol bémol (Gb)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-114",
    titre: "We Can't Be Friends",
    artiste: "Ariana Grande",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi (E)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-115",
    titre: "We Don't Talk Anymore",
    artiste: "Charlie Puth ft. Selena Gomez",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Do# mineur (C#-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-116",
    titre: "What's Up",
    artiste: "4 Non Blondes",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Fa (F)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-117",
    titre: "Where Is My Husband",
    artiste: "Amaarae",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : La mineur (A-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-118",
    titre: "Worth It",
    artiste: "Fifth Harmony",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Sol (G)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-119",
    titre: "Yesterday",
    artiste: "The Beatles",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : La (A)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-120",
    titre: "Your Song",
    artiste: "Elton John",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Si (B)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "song-121",
    titre: "Zombie",
    artiste: "The Cranberries",
    statut: "pret",
    formations: [],
    arrangementInfo: "Tonalité : Mi mineur (E-)",
    prestationIds: [],
    repetitionIds: [],
    audios: [],
    files: [],
    favorisUserIds: [],
    updatedAt: "2026-09-01T00:00:00Z",
  },
];
