import { CentralDocument } from "@/types/document";

export const INITIAL_MOCK_CENTRAL_DOCUMENTS: CentralDocument[] = [
  {
    id: "doc-101",
    nom: "Fiche_de_Paie_Juillet_2026_Constantin.pdf",
    type: "pdf",
    categorie: "administratif",
    dateAjout: "2026-08-01T10:00:00Z",
    addedBy: "Production Artefacts",
    taille: "420 KB",
    fileUrl: "/docs/fiche-paie-juillet.pdf",
    userId: "mus-1", // Constantin Lau
    description: "Fiche de paie officielle pour l'activité de juillet 2026",
  },
  {
    id: "doc-102",
    nom: "AEM_Attestation_Juin_2026_Constantin.pdf",
    type: "pdf",
    categorie: "administratif",
    dateAjout: "2026-07-05T09:00:00Z",
    addedBy: "Production Artefacts",
    taille: "280 KB",
    fileUrl: "/docs/aem-juin.pdf",
    userId: "mus-1",
    description: "Attestation AEM Pôle Emploi Spectacle",
  },
  {
    id: "doc-201",
    nom: "Fiche_de_Paie_Juillet_2026_Theo.pdf",
    type: "pdf",
    categorie: "administratif",
    dateAjout: "2026-08-01T10:00:00Z",
    addedBy: "Production Artefacts",
    taille: "415 KB",
    fileUrl: "/docs/fiche-paie-juillet-theo.pdf",
    userId: "mus-2", // Théo Lombard
  },
  {
    id: "doc-301",
    nom: "Partition_Piano_Chant_Shallow.pdf",
    type: "pdf",
    categorie: "musical",
    dateAjout: "2026-08-02T14:30:00Z",
    addedBy: "Constantin Lau",
    taille: "1.4 MB",
    fileUrl: "/docs/partition-shallow.pdf",
    songId: "song-1",
    songTitle: "Shallow",
    description: "Arrangement duo piano/chant tonalité Sol Majeur",
  },
  {
    id: "doc-302",
    nom: "Grille_iRealPro_LOVE.html",
    type: "html",
    categorie: "musical",
    dateAjout: "2026-08-03T11:15:00Z",
    addedBy: "Théo Lombard",
    taille: "85 KB",
    fileUrl: "/docs/ireal-love.html",
    songId: "song-2",
    songTitle: "L-O-V-E",
    description: "Grille d'accord iReal Pro de la prestation",
  },
  {
    id: "doc-401",
    nom: "Fiche_Technique_Chateau_Cassis.pdf",
    type: "pdf",
    categorie: "prestation",
    dateAjout: "2026-08-04T16:00:00Z",
    addedBy: "Julia Fabre",
    taille: "2.1 MB",
    fileUrl: "/docs/fiche-technique-cassis.pdf",
    prestationId: "prest-1",
    prestationTitle: "Mariage Émilie & Marc (Cassis)",
    description: "Implantation scène, accès traiteur et consignes sonores",
  },
  {
    id: "doc-501",
    nom: "Notes_Arrangements_Quartet_13Aout.pdf",
    type: "pdf",
    categorie: "repetition",
    dateAjout: "2026-08-05T18:00:00Z",
    addedBy: "Théo Lombard",
    taille: "650 KB",
    fileUrl: "/docs/notes-quartet.pdf",
    repetitionId: "rep-1",
    repetitionTitle: "Répétition Quartet (13 août)",
    description: "Structure des solos et fin de morceau de secours",
  },
];
