import { Song } from "@/types/song";

export const INITIAL_MOCK_SONGS: Song[] = [
  {
    id: "song-1",
    titre: "L-O-V-E",
    artiste: "Nat King Cole",
    statut: "pret",
    formations: ["Duo", "Trio", "Quartet", "XXL"],
    arrangementInfo: "Tonalité Sol Majeur (G). Intro 4 mesures piano solo. Thème au chant, solo guitare 16 mesures, retour au thème avec coda ralentie.",
    prestationIds: ["prest-1"], // Linked to Mariage Émilie & Marc
    repetitionIds: ["rep-1"], // Linked to Répétition Quartet
    audios: [
      {
        id: "audio-101",
        titre: "Take finale studio — Arrangement Quartet",
        url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        dateAjout: "2026-08-01",
        auteur: "Constantin Lau",
        description: "Version validée pour l'ouverture de bal.",
      },
      {
        id: "audio-102",
        titre: "Prise 1 — Test tempo piano solo",
        url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
        dateAjout: "2026-07-20",
        auteur: "Constantin Lau",
        description: "Première esquisse d'arrangement.",
      },
    ],
    files: [
      {
        id: "file-101",
        nom: "Partition_LOVE_Quartet_G.pdf",
        type: "partition",
        url: "#",
        taille: "420 KB",
        dateAjout: "2026-08-01",
        auteur: "Théo Lombard",
      },
      {
        id: "file-102",
        nom: "Grille_Chords_LOVE.html",
        type: "ireal",
        url: "#",
        taille: "15 KB",
        dateAjout: "2026-08-01",
      },
    ],
    favorisUserIds: ["mus-1", "mus-2", "mus-5"], // Marked favorite by Constantin, Théo, Marie
    updatedAt: "2026-08-01T14:00:00Z",
    updatedBy: "Constantin Lau",
  },
  {
    id: "song-2",
    titre: "Fly Me to the Moon",
    artiste: "Frank Sinatra",
    statut: "pret",
    formations: ["Duo", "Trio", "Quartet"],
    arrangementInfo: "Tonalité Do mineur / Mi bémol. Swing modéré. Solo basse au 2ème passage.",
    prestationIds: ["prest-1", "prest-2"],
    repetitionIds: ["rep-1"],
    audios: [
      {
        id: "audio-201",
        titre: "Maquette Duo Acoustique V2",
        url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
        dateAjout: "2026-08-05",
        auteur: "Théo Lombard",
        description: "Prise voix Marie + guitare Théo.",
      },
    ],
    files: [
      {
        id: "file-201",
        nom: "Grille_Fly_Me_To_The_Moon.pdf",
        type: "grille",
        url: "#",
        taille: "180 KB",
        dateAjout: "2026-08-02",
      },
    ],
    favorisUserIds: ["mus-2", "mus-5"],
    updatedAt: "2026-08-05T10:00:00Z",
  },
  {
    id: "song-3",
    titre: "Ain't No Mountain High Enough",
    artiste: "Marvin Gaye & Tammi Terrell",
    statut: "en_cours",
    formations: ["Quartet", "XXL"],
    arrangementInfo: "Changement de tonalité au dernier refrain. Attention à la relance batterie sur le bridge.",
    prestationIds: ["prest-1"],
    repetitionIds: ["rep-1", "rep-3"],
    audios: [
      {
        id: "audio-301",
        titre: "Extrait répétition — Test changement de tonalité",
        url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
        dateAjout: "2026-08-06",
        auteur: "Théo Lombard",
      },
    ],
    files: [
      {
        id: "file-301",
        nom: "Structure_Mountain.pdf",
        type: "partition",
        url: "#",
        taille: "310 KB",
      },
    ],
    favorisUserIds: ["mus-1"],
    updatedAt: "2026-08-06T18:00:00Z",
  },
  {
    id: "song-4",
    titre: "Shallow",
    artiste: "Lady Gaga & Bradley Cooper",
    statut: "a_travailler",
    formations: ["Duo"],
    arrangementInfo: "Duo chant + guitare acoustique. Caler les harmonies de voix sur le refrain final.",
    prestationIds: [],
    repetitionIds: ["rep-2"],
    audios: [],
    files: [],
    favorisUserIds: ["mus-5"],
    updatedAt: "2026-08-07T11:00:00Z",
  },
  {
    id: "song-5",
    titre: "Valerie",
    artiste: "Amy Winehouse",
    statut: "pret",
    formations: ["Duo", "Trio", "Quartet", "XXL"],
    arrangementInfo: "Tempo uptempo Motown. Coda répétée 4 fois en vamp.",
    prestationIds: ["prest-2"],
    repetitionIds: ["rep-2"],
    audios: [
      {
        id: "audio-501",
        titre: "Version Live Trio",
        url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
        dateAjout: "2026-07-15",
        auteur: "Constantin Lau",
      },
    ],
    files: [
      {
        id: "file-501",
        nom: "Partition_Valerie_Full.pdf",
        type: "partition",
        url: "#",
        taille: "520 KB",
      },
    ],
    favorisUserIds: ["mus-2", "mus-6"],
    updatedAt: "2026-07-15T16:00:00Z",
  },
];
