import {
  Home,
  Calendar,
  Music,
  Mic2,
  Package,
  FileText,
  CalendarOff,
  Users,
  User,
  Bell,
} from "lucide-react";
import { NavItem, NavCategory } from "@/types/navigation";

export const CATEGORY_LABELS: Record<NavCategory, string> = {
  operations: "Activité & Prestations",
  personal: "Mon Espace",
  management: "Gestion & Support",
};

export const NAVIGATION_ITEMS: NavItem[] = [
  {
    id: "accueil",
    label: "Accueil",
    href: "/",
    icon: Home,
    category: "operations",
    description: "Vue d'ensemble et prochains événements",
    isBottomTab: true,
  },
  {
    id: "calendrier",
    label: "Calendrier",
    href: "/calendrier",
    icon: Calendar,
    category: "operations",
    description: "Planning des prestations et événements",
    isBottomTab: true,
  },
  {
    id: "espace-musical",
    label: "Espace musical",
    href: "/espace-musical",
    icon: Music,
    category: "operations",
    description: "Repertoire, setlists, partitions et versions audio",
    isBottomTab: true,
  },
  {
    id: "repetitions",
    label: "Répétitions",
    href: "/repetitions",
    icon: Mic2,
    category: "operations",
    description: "Planning et suivi des séances de répétition",
  },
  {
    id: "materiel",
    label: "Matériel",
    href: "/materiel",
    icon: Package,
    category: "operations",
    description: "Gestion des kits, micros, son et instruments",
  },
  {
    id: "indisponibilites",
    label: "Mes indisponibilités",
    href: "/indisponibilites",
    icon: CalendarOff,
    category: "personal",
    description: "Saisir mes dates d'indisponibilité et congés",
  },
  {
    id: "annuaire",
    label: "Annuaire",
    href: "/annuaire",
    icon: Users,
    category: "personal",
    description: "Musiciens, techniciens et contacts utiles",
  },
  {
    id: "profil",
    label: "Profil",
    href: "/profil",
    icon: User,
    category: "personal",
    description: "Mes coordonnées, rôles et préférences",
    isBottomTab: true,
  },
  {
    id: "documents",
    label: "Documents",
    href: "/documents",
    icon: FileText,
    category: "management",
    description: "Centre documentaire unique : partitions, fiches techniques, contrats",
  },
  {
    id: "administratif",
    label: "Administratif",
    href: "/administratif",
    icon: FileText,
    category: "management",
    description: "Contrats, cachets, factures et documents officiels",
  },
  {
    id: "notifications",
    label: "Notifications",
    href: "/notifications",
    icon: Bell,
    category: "management",
    badge: 3,
    badgeVariant: "rose",
    description: "Rappels, alertes et annonces d'équipe",
    isBottomTab: true,
  },
];


